catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.BookListView.as_view(), name="index"),
    # path("books/", views.BookListView.as_view(), name="books"),
    path("books/<int:pk>", views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('borrowed/', views.LoanedBooksAllListView.as_view(), name='all-borrowed'),
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
    path('author/create/', views.AuthorCreate.as_view(), name='author-create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author-update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author-delete'),
    path('book/create/', views.BookCreate.as_view(), name='book-create'),
    path('book/<int:pk>/update/', views.BookUpdate.as_view(), name='book-update'),
    path('book/<int:pk>/delete/', views.BookDelete.as_view(), name='book-delete'),
    
    path('genre/<str:genre>', views.BookGenreListview.as_view(), name='book-genre'),
    path('book/<int:book_id>/instance/create/', views.BookInstanceCreateView.as_view(), name='bookinstance_create'),
    path('signup/', views.signup, name='signup'),
    path('search/', views.SearchResultsView.as_view(), name='book-search'),
    path('about-me/', views.about_me_view, name="about-me"),
    path('about-project/', views.about_project_view, name="about-project"),
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

# from catalog.views import CustomPasswordResetView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
    # path('accounts/password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
import uuid
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User


class Language(models.Model):
    """Model representing a Language (e.g. English, French, Japanese, etc.)"""

    name = models.CharField(
        max_length=200,
        help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)",
    )

    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.name


class Genre(models.Model):
    """Model representing a book genre."""

    name = models.CharField(
        max_length=200, help_text="Enter a book genre (e.g. Science Fiction)"
    )

    def __str__(self):
        """String for representing the Model object."""
        return self.name


class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""

    title = models.CharField(max_length=200)
    author = models.ForeignKey("Author", on_delete=models.SET_NULL, null=True)
    summary = models.TextField(
        max_length=1000, help_text="Enter a brief description of the book"
    )
    isbn = models.CharField(
        "ISBN",
        max_length=13,
        unique=True,
        help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>',
    )
    genre = models.ManyToManyField(Genre, help_text="Select a genre for this book")
    language = models.ForeignKey("Language", on_delete=models.SET_NULL, null=True)

    def __str__(self):
        """String for representing the Model object."""
        return self.title

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse("book-detail", args=[str(self.id)])

    def display_genre(self):
        """Create a string for the Genre. This is required to display genre in admin."""
        return ", ".join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = "Genre"


class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        help_text="Unique ID for this particular book across whole library",
    )
    book = models.ForeignKey("Book", on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ("m", "Maintenance"),
        ("o", "On loan"),
        ("a", "Available"),
        ("r", "Reserved"),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default="m",
        help_text="Book availability",
    )
    
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        ordering = ["due_back"]
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        """String for representing the Model object."""
        return f"{self.id} ({self.book.title})"
    
    @property
    def is_overdue(self):
        """Determines if the book is overdue based on due date and current date."""
        return bool(self.due_back and date.today() > self.due_back)


class Author(models.Model):
    """Model representing an author."""

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField("died", null=True, blank=True)

    class Meta:
        ordering = ["last_name", "first_name"]
        # permissions = (("can_create_author", "Create, Edit and Delete Authors"),)

    def get_absolute_url(self):
        """Returns the URL to access a particular author instance."""
        return reverse("author-detail", args={(self.id)})

    def __str__(self):
        """String for representing the Model object."""
        return f"{self.last_name}, {self.first_name}"

catalog/views.py
import datetime
import os

from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.contrib.auth.views import PasswordResetView
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.db.models import Q

from .models import Book, Author, BookInstance, Genre, Language
from catalog.forms import (
    RenewBookForm,
    CreateBookInstanceForm,
    CustomPasswordResetForm,
    CustomUserCreationForm,
)

# # Environment variables
# from dotenv import load_dotenv

# load_dotenv()

# # 3rd party packages
# from sendgrid import SendGridAPIClient
# from sendgrid.helpers.mail import Mail


# def index(request):
#     """View function for home page of site."""

#     # Generate counts of some of the main objects
#     num_books = Book.objects.all().count()
#     num_instances = BookInstance.objects.all().count()

#     # Available books (status = 'a')
#     num_instances_available = BookInstance.objects.filter(status__exact="a").count()

#     # The all() is implied by default.
#     num_authors = Author.objects.count()

#     # Counts for genres and books containing "fiction"
#     num_genres_fiction = Genre.objects.filter(name__icontains="fiction").count()
#     num_books_fiction = Book.objects.filter(title__icontains="fiction").count()

#     # Number of visits to this view, as counted in the session variable.
#     num_visits = request.session.get("num_visits", 0)
#     request.session["num_visits"] = num_visits + 1

#     context = {
#         "num_books": num_books,
#         "num_instances": num_instances,
#         "num_instances_available": num_instances_available,
#         "num_authors": num_authors,
#         "num_genres_fiction": num_genres_fiction,
#         "num_books_fiction": num_books_fiction,
#         "num_visits": num_visits,
#     }

#     # Render the HTML template index.html with the data in the context variable
#     return render(request, "index.html", context=context)


class BookListView(generic.ListView):
    model = Book
    context_object_name = "book_list"
    template_name = "index.html"
    paginate_by = 5

    def get_queryset(self):
        # return Book.objects.filter(title__icontains="fiction")[:5]
        return Book.objects.all()

    def get_context_data(self, **kwargs):
        context = super(BookListView, self).get_context_data(**kwargs)
        context["all_genre"] = Genre.objects.all()
        return context


class BookDetailView(generic.DetailView):
    model = Book
    context_object_name = "book"
    template_name = "book_detail.html"


class BookInstanceCreateView(LoginRequiredMixin, CreateView):
    model = BookInstance
    form_class = CreateBookInstanceForm
    # fields = ['imprint', 'due_back', 'status']
    # context_object_name = "bookinstance"
    template_name = "bookinstance_form.html"
    success_url = reverse_lazy("my-borrowed")

    def form_valid(self, form):
        form.instance.borrower = self.request.user
        form.instance.book = get_object_or_404(Book, id=self.kwargs["book_id"])
        form.instance.status = "o"
        return super().form_valid(form)

    def get_initial(self):
        initial = super().get_initial()
        initial["status"] = "o"  # Set status to "On loan"
        initial["borrower"] = self.request.user  # Set borrower to current user
        initial["book"] = get_object_or_404(
            Book, id=self.kwargs["book_id"]
        )  # Set book to clicked book
        return initial

    def get_context_data(self, **kwargs):
        context = super(BookInstanceCreateView, self).get_context_data(**kwargs)
        context["book"] = Book.objects.get(pk=self.kwargs["book_id"])
        context["form"] = self.get_form()
        return context


class AuthorListView(generic.ListView):
    model = Author
    context_object_name = "author_list"
    template_name = "author_list.html"
    paginate_by = 10


class AuthorDetailView(generic.DetailView):
    model = Author
    context_object_name = "author"
    template_name = "author_detail.html"
    paginate_by = 10


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """Generic class-based view listing books on loan to current user."""

    model = BookInstance
    template_name = "bookinstance_list.html"
    paginate_by = 10

    def get_queryset(self):
        return (
            BookInstance.objects.filter(borrower=self.request.user)
            .filter(status__exact="o")
            .order_by("due_back")
        )


class LoanedBooksAllListView(
    LoginRequiredMixin, PermissionRequiredMixin, generic.ListView
):
    """Generic class-based view listing all books on loan."""

    model = BookInstance
    template_name = "bookinstance_list_all.html"
    context_object_name = "bookinstance_list_all"
    paginate_by = 10
    permission_required = "catalog.can_mark_returned"

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact="o").order_by("due_back")


# Get all books with a particular genre
class BookGenreListview(generic.ListView):
    template_name = "book_list_by_genre.html"
    context_object_name = "books"
    paginate_by = 5

    def get_queryset(self):
        genre = self.kwargs["genre"]
        queryset = Book.objects.filter(genre__name__in=[genre])
        return queryset

    def get_context_data(self, **kwargs):
        context = super(BookGenreListview, self).get_context_data(**kwargs)
        context["genre"] = self.kwargs["genre"]
        context["all_genre"] = Genre.objects.all()
        return context


# as a function based view
# def book_detail_view(request, primary_key):
#     try:
#         book = Book.objects.get(pk=primary_key)
#     except Book.DoesNotExist:
#         raise Http404('Book does not exist')

#     return render(request, 'catalog/book_detail.html', context={'book': book})


@login_required
@permission_required("catalog.can_mark_returned", raise_exception=True)
def renew_book_librarian(request, pk):
    """View function for renewing a specific BookInstance by librarian."""
    book_instance = get_object_or_404(BookInstance, pk=pk)

    # If this is a POST request then process the Form data
    if request.method == "POST":
        # Create a form instance and populate it with data from the request (binding):
        form = RenewBookForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            book_instance.due_back = form.cleaned_data["renewal_date"]
            book_instance.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse("all-borrowed"))

    # If this is a GET (or any other method) create the default form.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={"renewal_date": proposed_renewal_date})

    context = {
        "form": form,
        "book_instance": book_instance,
    }

    return render(request, "book_renew_librarian.html", context)


class AuthorCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Author
    fields = ["first_name", "last_name", "date_of_birth", "date_of_death"]
    initial = {"date_of_death": "05/01/2023"}
    permission_required = "catalog.add_author"
    template_name = "author_form.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["creating"] = True
        return context


class AuthorUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Author
    fields = (
        "__all__"  # Not recommended (potential security issue if more fields added)
    )
    permission_required = "catalog.change_author"
    template_name = "author_form.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["creating"] = False
        return context


class AuthorDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Author
    success_url = reverse_lazy("authors")
    permission_required = "catalog.delete_author"
    template_name = "author_confirm_delete.html"


class BookCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Book
    fields = ["title", "author", "summary", "isbn", "genre", "language"]
    permission_required = "catalog.add_book"
    template_name = "book_form.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["creating"] = True
        return context


class BookUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Book
    fields = (
        "__all__"  # Not recommended (potential security issue if more fields added)
    )
    permission_required = "catalog.change_book"
    template_name = "book_form.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["creating"] = False
        return context


class BookDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Book
    success_url = reverse_lazy("index")
    permission_required = "catalog.delete_book"
    template_name = "book_confirm_delete.html"


# class CustomPasswordResetView(PasswordResetView):
#     form_class = CustomPasswordResetForm
#     template_name = "password_reset.html"
#     success_url = reverse_lazy("password_reset_done")

#     def form_valid(self, form):

catalog/templates/author_confirm_delete.html
{% extends 'base_generic.html' %}

{% load static %}

{% load widget_tweaks %}

{% block title %} <title>Reader | Delete Author</title> {% endblock title %}

{% block content %}
<div class="header text-center">
	<div class="container">
	  <div class="row">
		<div class="col-lg-9 mx-auto">
		  <h1 class="mb-4">Delete Author</h1>
		  <ul class="list-inline">
			<li class="list-inline-item"><a class="text-default" href="{% url 'index' %}">Home
				&nbsp; &nbsp; /</a></li>
			<li class="list-inline-item text-primary">Delete Author</li>
		  </ul>
		</div>
	  </div>
	</div>
  
	<svg class="header-shape-1" width="39" height="40" viewBox="0 0 39 40" fill="none" xmlns="http://www.w3.org/2000/svg">
	  <path d="M0.965848 20.6397L0.943848 38.3906L18.6947 38.4126L18.7167 20.6617L0.965848 20.6397Z" stroke="#040306"
		stroke-miterlimit="10" />
	  <path class="path" d="M10.4966 11.1283L10.4746 28.8792L28.2255 28.9012L28.2475 11.1503L10.4966 11.1283Z" />
	  <path d="M20.0078 1.62949L19.9858 19.3804L37.7367 19.4024L37.7587 1.65149L20.0078 1.62949Z" stroke="#040306"
		stroke-miterlimit="10" />
	</svg>
  
  
	<svg class="header-shape-2" width="39" height="39" viewBox="0 0 39 39" fill="none" xmlns="http://www.w3.org/2000/svg">
	  <g filter="url(#filter0_d)">
		<path class="path"
		  d="M24.1587 21.5623C30.02 21.3764 34.6209 16.4742 34.435 10.6128C34.2491 4.75147 29.3468 0.1506 23.4855 0.336498C17.6241 0.522396 13.0233 5.42466 13.2092 11.286C13.3951 17.1474 18.2973 21.7482 24.1587 21.5623Z" />
		<path
		  d="M5.64626 20.0297C11.1568 19.9267 15.7407 24.2062 16.0362 29.6855L24.631 29.4616L24.1476 10.8081L5.41797 11.296L5.64626 20.0297Z"
		  stroke="#040306" stroke-miterlimit="10" />
	  </g>
	  <defs>
		<filter id="filter0_d" x="0.905273" y="0" width="37.8663" height="38.1979" filterUnits="userSpaceOnUse"
		  color-interpolation-filters="sRGB">
		  <feFlood flood-opacity="0" result="BackgroundImageFix" />
		  <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" />
		  <feOffset dy="4" />
		  <feGaussianBlur stdDeviation="2" />
		  <feColorMatrix type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.25 0" />
		  <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow" />
		  <feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow" result="shape" />
		</filter>
	  </defs>
	</svg>
  
  
	<svg class="header-shape-3" width="39" height="40" viewBox="0 0 39 40" fill="none" xmlns="http://www.w3.org/2000/svg">
	  <path d="M0.965848 20.6397L0.943848 38.3906L18.6947 38.4126L18.7167 20.6617L0.965848 20.6397Z" stroke="#040306"
		stroke-miterlimit="10" />
	  <path class="path" d="M10.4966 11.1283L10.4746 28.8792L28.2255 28.9012L28.2475 11.1503L10.4966 11.1283Z" />
	  <path d="M20.0078 1.62949L19.9858 19.3804L37.7367 19.4024L37.7587 1.65149L20.0078 1.62949Z" stroke="#040306"
		stroke-miterlimit="10" />
	</svg>
  
  
	<svg class="header-border" height="240" viewBox="0 0 2202 240" fill="none" xmlns="http://www.w3.org/2000/svg">
	  <path
		d="M1 123.043C67.2858 167.865 259.022 257.325 549.762 188.784C764.181 125.427 967.75 112.601 1200.42 169.707C1347.76 205.869 1901.91 374.562 2201 1"
		stroke-width="2" />
	</svg>
  </div>
  
  <section class="section-sm">
	<div class="container">
	  <div class="row">
		<div class="col-lg-8 mx-auto">
  
		  <div class="content mb-3">
			<h2>Delete {{ author }}&hellip;.</h2>
		  </div>
		  <p><strong>Are you sure you want to delete the author: {{ author }}?</strong></p>

		  <form method="POST" action="#">
			{% csrf_token %}
			{{ form.non_field_errors }}
  
			<input type="submit" value="submit" class="btn btn-primary">
		  </form>
  
		  
  
		</div>
	  </div>
	</div>
  </section>
  
{% endblock content %}

catalog/templates/book_detail.html
{% extends 'base_generic.html' %}

{% load static %}

{% block title %}<title>Book | {{ book.title }}</title>{% endblock title %}

{% block content %}
<div class="author">
	<div class="container">
		<div class="row no-gutters justify-content-center">
			{% comment %} <div class="col-lg-3 col-md-4 mb-4 mb-md-0">

				<img class="author-image"
					src="https://www.gravatar.com/avatar/e631284a67e89a04627f7c917d0fa145?s=320&pg&d=identicon">

			</div> {% endcomment %}
			<div class="col-md-8 col-lg-6 text-center text-md-left">
				<h2 class="mb-2">{{ book.title }} </h2>
				<strong class="mb-2 d-block">
					<a href="{{ book.author.get_absolute_url }}" class="card-meta-author">
						{{ book.author }}
					</a>
				</strong>
				<ul class="card-meta list-inline">
					<li class="list-inline-item">
						{{ book.language }}
					</li>
					<li class="list-inline-item">
						<ul class="card-meta-tag list-inline">
							{% for genre in book.genre.all %}
							<li class="list-inline-item"><a href="{% url 'book-genre' genre %}">{{ genre }}</a></li>
							{% endfor %}
						</ul>
					</li>
				</ul>

				<div class="post-count mb-1"><span class="text-primary">ISBN:</span> {{ book.isbn }}</div>

				<div class="content">
					<p>{{ book.summary }}</p>

				</div>

				<a href="{% url 'bookinstance_create' book.id %}" class="btn btn-outline-primary">Borrow</a>
				{% if perms.catalog.add_book %}
				<a href="{% url 'book-update' book.pk %}" class="ms-5 btn btn-success">Update</a>
				<a href="{% url 'book-delete' book.pk %}" class="btn btn-danger">Delete</a>
				{% endif %}
			</div>
		</div>
	</div>

	<svg class="author-shape-1" width="39" height="40" viewBox="0 0 39 40" fill="none"
		xmlns="http://www.w3.org/2000/svg">
		<path d="M0.965848 20.6397L0.943848 38.3906L18.6947 38.4126L18.7167 20.6617L0.965848 20.6397Z" stroke="#040306"
			stroke-miterlimit="10" />
		<path class="path" d="M10.4966 11.1283L10.4746 28.8792L28.2255 28.9012L28.2475 11.1503L10.4966 11.1283Z" />
		<path d="M20.0078 1.62949L19.9858 19.3804L37.7367 19.4024L37.7587 1.65149L20.0078 1.62949Z" stroke="#040306"
			stroke-miterlimit="10" />
	</svg>


	<svg class="author-shape-2" width="39" height="39" viewBox="0 0 39 39" fill="none"
		xmlns="http://www.w3.org/2000/svg">
		<g filter="url(#filter0_d)">
			<path class="path"
				d="M24.1587 21.5623C30.02 21.3764 34.6209 16.4742 34.435 10.6128C34.2491 4.75147 29.3468 0.1506 23.4855 0.336498C17.6241 0.522396 13.0233 5.42466 13.2092 11.286C13.3951 17.1474 18.2973 21.7482 24.1587 21.5623Z" />
			<path
				d="M5.64626 20.0297C11.1568 19.9267 15.7407 24.2062 16.0362 29.6855L24.631 29.4616L24.1476 10.8081L5.41797 11.296L5.64626 20.0297Z"
				stroke="#040306" stroke-miterlimit="10" />
		</g>
		<defs>
			<filter id="filter0_d" x="0.905273" y="0" width="37.8663" height="38.1979" filterUnits="userSpaceOnUse"
				color-interpolation-filters="sRGB">
				<feFlood flood-opacity="0" result="BackgroundImageFix" />
				<feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" />
				<feOffset dy="4" />
				<feGaussianBlur stdDeviation="2" />
				<feColorMatrix type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.25 0" />
				<feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow" />
				<feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow" result="shape" />
			</filter>
		</defs>
	</svg>


	<svg class="author-shape-3" width="39" height="40" viewBox="0 0 39 40" fill="none"
		xmlns="http://www.w3.org/2000/svg">
		<path d="M0.965848 20.6397L0.943848 38.3906L18.6947 38.4126L18.7167 20.6617L0.965848 20.6397Z" stroke="#040306"
			stroke-miterlimit="10" />
		<path class="path" d="M10.4966 11.1283L10.4746 28.8792L28.2255 28.9012L28.2475 11.1503L10.4966 11.1283Z" />
		<path d="M20.0078 1.62949L19.9858 19.3804L37.7367 19.4024L37.7587 1.65149L20.0078 1.62949Z" stroke="#040306"
			stroke-miterlimit="10" />
	</svg>


	<svg class="author-border" height="240" viewBox="0 0 2202 240" fill="none" xmlns="http://www.w3.org/2000/svg">
		<path
			d="M1 123.043C67.2858 167.865 259.022 257.325 549.762 188.784C764.181 125.427 967.75 112.601 1200.42 169.707C1347.76 205.869 1901.91 374.562 2201 1"
			stroke-width="2" />
	</svg>
</div>

<section class="section-sm" id="post">
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-lg-8 mb-5 mb-lg-0">
				<h2 class="h5 section-title">Book Copies</h2>

				{% for copy in book.bookinstance_set.all %}
				<article class="card mb-4">
					<div class="row card-body">
						<div class="col-12">
							<p
								class="{% if copy.status == 'a' %} text-success {% elif copy.status == 'm' %} text-danger {% else %} text-warning {% endif %}">
								<strong>Status: </strong> {{ copy.get_status_display }}
							</p>
							{% if copy.status != 'a' %}
							<p class="{% if copy.is_overdue %}text-danger{% endif %}"><strong>Due back: </strong> {{ copy.due_back }} </p>
							{% endif %}
							<p><strong>Imprint:</strong> {{ copy.imprint }} </p>
							<p class='text-muted'><strong>Id: </strong>{{ copy.id }}</p>
							{% if user.is_authenticated %}
							<a href="{% url 'renew-book-librarian' copy.id %}" class="btn btn-outline-primary">Renew Book</a>

							{% endif %}
						</div>
					</div>
				</article>
				{% endfor %}

				<!-- Pagination -->
				<ul class="pagination justify-content-center">
					{% if is_paginated %}
					<li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
						<a class="page-link"
							href="{% if page_obj.has_previous %}?page={{ page_obj.previous_page_number }}{% endif %}"
							aria-label="Previous">
							<span aria-hidden="true">&laquo;</span>
							<span class="sr-only">Previous</span>
						</a>
					</li>
					{% for page_num in page_obj.paginator.page_range %}
					<li class="page-item {% if page_num == page_obj.number %}active{% endif %}">
						<a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
					</li>
					{% endfor %}
					<li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
						<a class="page-link"
							href="{% if page_obj.has_next %}?page={{ page_obj.next_page_number }}{% endif %}"
							aria-label="Next">
							<span aria-hidden="true">&raquo;</span>
							<span class="sr-only">Next</span>
						</a>
					</li>
					{% endif %}
				</ul>


			</div>
		</div>
	</div>
</section>

{% endblock content %}